{
    try {
        // Escribir el ejercicio aquí!
        // Dentro de este bloque try


    } catch (err) {
        console.log("El ejercicio 21 está devolviendo un error. Checkea el código...");
        console.error(err);
    }
}
